.\" Manpage for lab_urjc.
.\" Contact jeiko.dev@gmail.com to correct errors or typos.
.TH man 1 "09 Jul 2022" "1.0" "lab_urjc man page"
.SH NAME
lab_urjc \- connect to Urjc laboratories server
.SH SYNOPSIS
lab_urjc <password>
.SH DESCRIPTION
lab_urjc is is a script that allows you to automatically connect to the Urjc laboratories server in Fuenlabrada.
.SH OPTIONS
The lab_urjc does not take any options. 
.SH BUGS
No known bugs.
.SH AUTHOR
Jeiko (jeiko.dev@gmail.com)
